Repository pomerium/desktop-client, pull requests merged in 2022-02, with the labels that each got.

#91 replaces discard button with back button on connection edit form
  .gitignore
  src/renderer/components/BeforeBackActionDialog.tsx
  src/renderer/pages/ConnectForm.tsx
Labels: accepted

#96 ci: rename master to main
  .github/workflows/publish.yml
  src/package.json
Labels: ci

#94 adds client cert fields
  api.proto
  desktop-client.iml
  package.json
  src/renderer/components/CertDetails.tsx
  src/renderer/pages/ConnectForm.tsx
  src/renderer/pages/ConnectionView.tsx
  src/renderer/pages/ManageConnections.tsx
  src/shared/pb/api.ts
  yarn.lock
Labels: enhancement
