Repository pomerium/desktop-client, pull requests merged in 2022-04, with the labels that each got.

#111 export: support exporting connections with tags
  .eslintrc.js
  src/main.dev.ts
  src/renderer/components/ConnectionRow.tsx
  src/renderer/components/ExportDialog.tsx
  src/renderer/components/TagFolderRow.tsx
  src/renderer/pages/ConnectionView.tsx
  src/renderer/pages/ManageConnections.tsx
  src/shared/constants.ts
Labels: enhancement

#110 ci: set explicit token permissions
  .github/workflows/publish.yml
  .github/workflows/test.yml
Labels: ci

#113 bump cli to 0.17.1
  package.json
Labels: bug

#116 add mui 5 styles
  package.json
  src/App.tsx
  src/renderer/components/Card.tsx
  src/renderer/components/CertDetails.tsx
  src/renderer/components/ConnectionRow.tsx
  src/renderer/components/ExportDialog.tsx
  src/renderer/components/FieldWrapper.tsx
  src/renderer/components/StyledCard.tsx
  src/renderer/components/TextField.tsx
  src/renderer/components/TopBar.tsx
  src/renderer/components/TopTabs.tsx
  src/renderer/icons/ClosedFolder.tsx
  src/renderer/icons/Connected.tsx
  src/renderer/icons/Delete.tsx
  src/renderer/icons/Disconnected.tsx
  src/renderer/icons/Edit.tsx
  src/renderer/icons/Export.tsx
  src/renderer/icons/ExportJSON.tsx
  src/renderer/icons/Logo.tsx
  src/renderer/icons/OpenFolder.tsx
  src/renderer/icons/VirtualClosedFolder.tsx
  src/renderer/icons/VirtualOpenFolder.tsx
  src/renderer/pages/ConnectForm.tsx
  src/renderer/pages/ConnectionView.tsx
  src/renderer/pages/ManageConnections.tsx
  src/shared/theme.ts
  yarn.lock
Labels: frontend, improvement

#118 notify tap of releases
  .github/workflows/notify-tap.yml
Labels: improvement
