Repository pomerium/desktop-client, pull requests merged in 2022-03, with the labels that each got.

#101 add error check for export
  src/main.dev.ts
Labels: bug

#103 Mui5upgrade
  package.json
  src/App.tsx
  src/main.prod.js.LICENSE.txt
  src/renderer/components/BeforeBackActionDialog.tsx
  src/renderer/components/Card.tsx
  src/renderer/components/CertDetails.tsx
  src/renderer/components/ConfirmationDialog.tsx
  src/renderer/components/ConnectionRow.tsx
  src/renderer/components/FieldWrapper.tsx
  src/renderer/components/SnackbarCloseButton.tsx
  src/renderer/components/TagFolderRow.tsx
  src/renderer/components/TextField.tsx
  src/renderer/components/TopBar.tsx
  src/renderer/components/TopTabs.tsx
  src/renderer/components/VirtualFolderRow.tsx
  src/renderer/icons/ClosedFolder.tsx
  src/renderer/icons/Connected.tsx
  src/renderer/icons/Delete.tsx
  src/renderer/icons/Disconnected.tsx
  src/renderer/icons/Edit.tsx
  src/renderer/icons/Export.tsx
  src/renderer/icons/ExportJSON.tsx
  src/renderer/icons/Logo.tsx
  src/renderer/icons/OpenFolder.tsx
  src/renderer/icons/VirtualClosedFolder.tsx
  src/renderer/icons/VirtualOpenFolder.tsx
  src/renderer/pages/ConnectForm.tsx
  src/renderer/pages/ConnectionView.tsx
  src/renderer/pages/ManageConnections.tsx
  src/shared/shadows.ts
  src/shared/theme.ts
  yarn.lock
Labels: dependencies, improvement

#102 deps: bump cli to v0.17
  package.json
Labels: dependencies

#105 remove workaround that is no longer needed
  package.json
  yarn.lock
Labels: improvement

#106 main: pick a random port for the cli
  .node-version
  src/cli.ts
  src/main.dev.ts
Labels: bug

#108 prevent app spawning multiple times (windows)
  src/main.dev.ts
Labels: bug
