Repository pomerium/desktop-client, pull requests merged in 2022-01, with the labels that each got.

#70 Update Destination field label and helper
  src/renderer/pages/ConnectForm.tsx
Labels: frontend, docs

#74 show confirmation dialog before deleting all connections by tag
  src/renderer/components/ConfirmationDialog.tsx
  src/renderer/components/TagFolderRow.tsx
Labels: bug

#78 Update confirmation punctuation.
  src/renderer/components/TagFolderRow.tsx
Labels: frontend, docs

#80 cleanup connection messages
  src/renderer/pages/ConnectionView.tsx
Labels: bug

#83 add error handler for api process quit
  src/main.dev.ts
Labels: improvement

#84 initialize api server with sentry dsn
  src/main.dev.ts
Labels: improvement

#85 Bump version for next release
  src/package.json
Labels: ci

#88 bump to 0.16.1 cli
  package.json
Labels: dependencies

#89 add upload icon
  src/renderer/pages/ManageConnections.tsx
Labels: frontend, nit

#87 add extra protection in main thread
  src/main.dev.ts
  src/renderer/components/TagFolderRow.tsx
  src/renderer/components/VirtualFolderRow.tsx
Labels: bug, improvement
